In [1]:
import pandas as pd

In [2]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25,30]}
df = pd.DataFrame(data)

In [3]:
lst = [['Alice', 25], ['Bob', 30]]
df2 = pd.DataFrame(lst, columns = ['Name', 'Age'])

In [4]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [7]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [8]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: object

In [9]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [11]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [13]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [14]:
df['Gender'] = ['F', 'M']
df.drop('Age', axis=1, inplace=True)

In [15]:
df

    Name Gender
0  Alice      F
1    Bob      M

In [16]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [17]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [18]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [23]:
df3.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [22]:
df3 = pd.merge(df, df2, on='Name')

In [ ]:
df.join(df3)

In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df.to_csv('output.csv', index=False)

In [29]:
df3.sort_values('Age')

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [30]:
df3['Age'].apply(lambda x: x+1)

0    26
1    31
Name: Age, dtype: int64

In [31]:
df3['Name'].unique()

array(['Alice', 'Bob'], dtype=object)

In [33]:
df3['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64